-- AddTelegramUserFields
ALTER TABLE "users" 
ADD COLUMN IF NOT EXISTS "telegram_id" BIGINT UNIQUE,
ADD COLUMN IF NOT EXISTS "is_bot" BOOLEAN,
ADD COLUMN IF NOT EXISTS "first_name" TEXT,
ADD COLUMN IF NOT EXISTS "last_name" TEXT,
ADD COLUMN IF NOT EXISTS "username" TEXT,
ADD COLUMN IF NOT EXISTS "language_code" TEXT,
ADD COLUMN IF NOT EXISTS "is_premium" BOOLEAN,
ADD COLUMN IF NOT EXISTS "added_to_attachment_menu" BOOLEAN,
ADD COLUMN IF NOT EXISTS "allows_write_to_pm" BOOLEAN,
ADD COLUMN IF NOT EXISTS "photo_url" TEXT,
ADD COLUMN IF NOT EXISTS "last_opened_at" TIMESTAMP(3);
